services:
  db:
    image: postgres:12.19-alpine3.20
    restart: always
    env_file:
      - .env
    

  web:
    build: .
    ports:
      - 8111:8181
    depends_on:
      - db
    command: ["uvicorn", "main:app", "--host=0.0.0.0","--port=8181"]